"""initial_schema

Revision ID: 3216c592b58f
Revises: 
Create Date: 2026-05-15 21:15:25.431950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3216c592b58f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'tutor', 'admin', 'parent', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_user_id'), 'users', ['discord_user_id'], unique=True)
    op.create_table('class_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year_level', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('discord_role_id', sa.BigInteger(), nullable=True),
    sa.Column('discord_text_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('discord_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('tutor_user_id', sa.Integer(), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_groups_discord_voice_channel_id'), 'class_groups', ['discord_voice_channel_id'], unique=False)
    op.create_table('class_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('student', 'tutor', name='memberrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_group_members_class_group_id'), 'class_group_members', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_class_group_members_user_id'), 'class_group_members', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('meet_link', sa.String(length=512), nullable=True),
    sa.Column('discord_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'active', 'completed', 'cancelled', name='lessonstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_class_group_id'), 'lessons', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_lessons_google_event_id'), 'lessons', ['google_event_id'], unique=True)
    op.create_index(op.f('ix_lessons_start_time'), 'lessons', ['start_time'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('present', 'late', 'left_early', 'absent', 'unknown', name='attendancestatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('marked_by', sa.Enum('system', 'tutor', 'admin', name='markedby'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_lesson_id'), 'attendance_records', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_user_id'), 'attendance_records', ['user_id'], unique=False)
    op.create_table('homework_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_tasks_class_group_id'), 'homework_tasks', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_homework_tasks_lesson_id'), 'homework_tasks', ['lesson_id'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Enum('dm', 'class_channel', name='reminderchannel'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_logs_lesson_id'), 'reminder_logs', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_user_id'), 'reminder_logs', ['user_id'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discord_voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sessions_lesson_id'), 'voice_sessions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_user_id'), 'voice_sessions', ['user_id'], unique=False)
    op.create_table('homework_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homework_task_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachment_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'late', 'missing', 'reviewed', name='submissionstatus'), nullable=False),
    sa.Column('tutor_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['homework_task_id'], ['homework_tasks.id'], ),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_submissions_homework_task_id'), 'homework_submissions', ['homework_task_id'], unique=False)
    op.create_index(op.f('ix_homework_submissions_student_user_id'), 'homework_submissions', ['student_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homework_submissions_student_user_id'), table_name='homework_submissions')
    op.drop_index(op.f('ix_homework_submissions_homework_task_id'), table_name='homework_submissions')
    op.drop_table('homework_submissions')
    op.drop_index(op.f('ix_voice_sessions_user_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_lesson_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index(op.f('ix_reminder_logs_user_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_lesson_id'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index(op.f('ix_homework_tasks_lesson_id'), table_name='homework_tasks')
    op.drop_index(op.f('ix_homework_tasks_class_group_id'), table_name='homework_tasks')
    op.drop_table('homework_tasks')
    op.drop_index(op.f('ix_attendance_records_user_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_lesson_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_lessons_start_time'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_google_event_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_class_group_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_class_group_members_user_id'), table_name='class_group_members')
    op.drop_index(op.f('ix_class_group_members_class_group_id'), table_name='class_group_members')
    op.drop_table('class_group_members')
    op.drop_index(op.f('ix_class_groups_discord_voice_channel_id'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_users_discord_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
