"""attendance_unique_constraint

Add a composite UNIQUE constraint on attendance_records(lesson_id, user_id)
so at most one attendance row can exist per (lesson, user). Without it the
SELECT-then-INSERT in get_or_create_attendance_record can race under concurrent
Discord voice events and create duplicate rows, splitting total_minutes and
risking MultipleResultsFound (DEF-22 / M1).

This migration is hand-written (NOT autogenerated) so it carries ONLY this
change. The SQLAlchemy models under-declare a few pre-existing portal-mirror
constraints/indexes relative to the portal_schema migration (e.g. the unique
constraints on parent_profiles.email, portal_credentials.invite_token and
student_profiles.user_id, plus some legacy index names). Running autogenerate
would sweep those into this migration and DROP those real uniqueness guarantees,
so migrations here must be authored by hand until that model drift is reconciled.

Day-zero assumption: this rides the deploy packet onto a fresh, EMPTY database,
so no de-duplication step is needed. If it is ever applied to a populated DB,
pre-existing duplicate (lesson_id, user_id) rows must be merged first or the
ADD CONSTRAINT will fail — which is the correct fail-closed behaviour.

Revision ID: f1a2b3c4d5e6
Revises: a1b2c3d4e5f6
Create Date: 2026-07-26 00:00:00.000000
"""
from typing import Sequence, Union

from alembic import op


revision: str = "f1a2b3c4d5e6"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CONSTRAINT_NAME = "uq_attendance_lesson_user"


def upgrade() -> None:
    # batch_alter_table keeps this portable: on PostgreSQL it emits a plain
    # ALTER TABLE ... ADD CONSTRAINT; on SQLite it falls back to table-copy.
    with op.batch_alter_table("attendance_records") as batch_op:
        batch_op.create_unique_constraint(
            CONSTRAINT_NAME, ["lesson_id", "user_id"]
        )


def downgrade() -> None:
    with op.batch_alter_table("attendance_records") as batch_op:
        batch_op.drop_constraint(CONSTRAINT_NAME, type_="unique")
